const actionTypes = {
  FETCH_FORECAST_START: "FETCH_FORECAST_START",
  FETCH_FORECAST_SUCCESS: "FETCH_FORECAST_SUCCESS",
  FETCH_FORECAST_FAILURE: "FETCH_FORECAST_FAILURE",

  FETCH_COORDS_START: "FETCH_COORDS_START",
  FETCH_COORDS_SUCCESS: "FETCH_COORDS_SUCCESS",
  FETCH_COORDS_FAILURE: "FETCH_COORDS_FAILURE",
};

export default actionTypes;